# algorithm
algorithm: 'aldi_vanilla'
discord_file: 'discords_aldi_gpu.csv'
seed: 13

# data
data_location: 'data/ashrae-energy-prediction'
discord_location: 'data/pred_discord'
output_location: 'data/preprocessed'

