# algorithm
algorithm: 'discords_aldi_gmm_weight_D-gmm_max_10'
discord_file: 'discords_aldi_gmm_weight_D-gmm_max_10.csv'
seed: 13

# data
data_location: 'data/ashrae-energy-prediction'
discord_location: 'data/pred_discord'
output_location: 'data/preprocessed'

