# algorithm
algorithm: 'discord_aldi_manuel_threshold_D'
discord_file: 'discord_aldi_manuel_threshold_D.csv'
seed: 13

# data
data_location: 'data/ashrae-energy-prediction'
discord_location: 'data/pred_discord'
output_location: 'data/preprocessed'
